// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/service.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountDropsRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Game                 string   `protobuf:"bytes,2,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDropsRequest) Reset()         { *m = AccountDropsRequest{} }
func (m *AccountDropsRequest) String() string { return proto.CompactTextString(m) }
func (*AccountDropsRequest) ProtoMessage()    {}
func (*AccountDropsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{0}
}

func (m *AccountDropsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDropsRequest.Unmarshal(m, b)
}
func (m *AccountDropsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDropsRequest.Marshal(b, m, deterministic)
}
func (m *AccountDropsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDropsRequest.Merge(m, src)
}
func (m *AccountDropsRequest) XXX_Size() int {
	return xxx_messageInfo_AccountDropsRequest.Size(m)
}
func (m *AccountDropsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDropsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDropsRequest proto.InternalMessageInfo

func (m *AccountDropsRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AccountDropsRequest) GetGame() string {
	if m != nil {
		return m.Game
	}
	return ""
}

type AccountDropsResponse struct {
	Item                 string   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDropsResponse) Reset()         { *m = AccountDropsResponse{} }
func (m *AccountDropsResponse) String() string { return proto.CompactTextString(m) }
func (*AccountDropsResponse) ProtoMessage()    {}
func (*AccountDropsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{1}
}

func (m *AccountDropsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDropsResponse.Unmarshal(m, b)
}
func (m *AccountDropsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDropsResponse.Marshal(b, m, deterministic)
}
func (m *AccountDropsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDropsResponse.Merge(m, src)
}
func (m *AccountDropsResponse) XXX_Size() int {
	return xxx_messageInfo_AccountDropsResponse.Size(m)
}
func (m *AccountDropsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDropsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDropsResponse proto.InternalMessageInfo

func (m *AccountDropsResponse) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

type AccountLookupRequest struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformID           string   `protobuf:"bytes,2,opt,name=platformID,proto3" json:"platformID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountLookupRequest) Reset()         { *m = AccountLookupRequest{} }
func (m *AccountLookupRequest) String() string { return proto.CompactTextString(m) }
func (*AccountLookupRequest) ProtoMessage()    {}
func (*AccountLookupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{2}
}

func (m *AccountLookupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountLookupRequest.Unmarshal(m, b)
}
func (m *AccountLookupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountLookupRequest.Marshal(b, m, deterministic)
}
func (m *AccountLookupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountLookupRequest.Merge(m, src)
}
func (m *AccountLookupRequest) XXX_Size() int {
	return xxx_messageInfo_AccountLookupRequest.Size(m)
}
func (m *AccountLookupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountLookupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountLookupRequest proto.InternalMessageInfo

func (m *AccountLookupRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *AccountLookupRequest) GetPlatformID() string {
	if m != nil {
		return m.PlatformID
	}
	return ""
}

type AccountLookupResponse struct {
	AccountID            string   `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountLookupResponse) Reset()         { *m = AccountLookupResponse{} }
func (m *AccountLookupResponse) String() string { return proto.CompactTextString(m) }
func (*AccountLookupResponse) ProtoMessage()    {}
func (*AccountLookupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{3}
}

func (m *AccountLookupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountLookupResponse.Unmarshal(m, b)
}
func (m *AccountLookupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountLookupResponse.Marshal(b, m, deterministic)
}
func (m *AccountLookupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountLookupResponse.Merge(m, src)
}
func (m *AccountLookupResponse) XXX_Size() int {
	return xxx_messageInfo_AccountLookupResponse.Size(m)
}
func (m *AccountLookupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountLookupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountLookupResponse proto.InternalMessageInfo

func (m *AccountLookupResponse) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec64d44e618a02a6, []int{4}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AccountDropsRequest)(nil), "twirp.accounts.AccountDropsRequest")
	proto.RegisterType((*AccountDropsResponse)(nil), "twirp.accounts.AccountDropsResponse")
	proto.RegisterType((*AccountLookupRequest)(nil), "twirp.accounts.AccountLookupRequest")
	proto.RegisterType((*AccountLookupResponse)(nil), "twirp.accounts.AccountLookupResponse")
	proto.RegisterType((*Empty)(nil), "twirp.accounts.Empty")
}

func init() { proto.RegisterFile("rpc/service.proto", fileDescriptor_ec64d44e618a02a6) }

var fileDescriptor_ec64d44e618a02a6 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2a, 0x48, 0xd6,
	0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2b,
	0x29, 0xcf, 0x2c, 0x2a, 0xd0, 0x4b, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x29, 0x56, 0xb2, 0xe4,
	0x12, 0x76, 0x84, 0xb0, 0x5d, 0x8a, 0xf2, 0x0b, 0x8a, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b,
	0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32, 0x53,
	0x84, 0x84, 0xb8, 0x58, 0xd2, 0x13, 0x73, 0x53, 0x25, 0x98, 0xc0, 0x22, 0x60, 0xb6, 0x92, 0x16,
	0x97, 0x08, 0xaa, 0xd6, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x90, 0xda, 0xcc, 0x92, 0xd4, 0x5c,
	0xa8, 0x6e, 0x30, 0x5b, 0x29, 0x08, 0xae, 0xd6, 0x27, 0x3f, 0x3f, 0xbb, 0xb4, 0x00, 0x66, 0x8f,
	0x14, 0x17, 0x47, 0x41, 0x4e, 0x62, 0x49, 0x5a, 0x7e, 0x11, 0x4c, 0x3d, 0x9c, 0x2f, 0x24, 0xc7,
	0xc5, 0x05, 0x63, 0x7b, 0xba, 0x40, 0x6d, 0x46, 0x12, 0x51, 0x32, 0xe5, 0x12, 0x45, 0x33, 0x13,
	0xea, 0x00, 0x19, 0x2e, 0x4e, 0xa8, 0xff, 0x3c, 0x5d, 0xa0, 0xa6, 0x22, 0x04, 0x94, 0xd8, 0xb9,
	0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x8d, 0xce, 0x32, 0x72, 0xf1, 0x43, 0x0d, 0x28, 0x0e, 0x86,
	0x04, 0x92, 0x50, 0x14, 0x17, 0x6f, 0x40, 0x69, 0x71, 0x46, 0x48, 0x3e, 0x54, 0x42, 0x48, 0x59,
	0x0f, 0x35, 0xc0, 0xf4, 0xb0, 0x84, 0x96, 0x94, 0x0a, 0x7e, 0x45, 0x50, 0x67, 0xc5, 0x71, 0xf1,
	0x7b, 0x16, 0xc3, 0x5c, 0x9c, 0x99, 0x97, 0x9d, 0x9a, 0x22, 0x84, 0x4b, 0x23, 0x4a, 0x20, 0x49,
	0xa9, 0x12, 0x50, 0x05, 0x31, 0xdf, 0x89, 0x35, 0x8a, 0xb9, 0xa8, 0x20, 0x39, 0x89, 0x0d, 0x1c,
	0xd1, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0x43, 0xf7, 0xf5, 0xfd, 0x01, 0x00, 0x00,
}
